### ISSUE TITLE
Feature request: support BullMQ

### ISSUE THREAD

**Issue by Niek** [rosslavery/k8s-bull-autoscaler#7]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Great project! Would you consider supporting BullMQ too? Or is that out of scope?

Relevant URLs:
https://github.com/taskforcesh/bullmq
https://docs.bullmq.io/
https://medium.com/@rockstudillo/beta-release-of-bullmq-4-0-867960aec51

*Edit*: looking at the source, I think we can use any type of queue as long as the JSON endpoint returns a number?

**Comment by rosslavery** [comment]
Apologies for the (extremely) long delay in responding here. Yes, technically this is queue-agnostic. It just needs to hit an endpoint that will respond with a count of messages in the queue and it will modify the replicas count of the specified deployment accordingly.
